spring:
  application:
    name: opensourceiq-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/opensourceiq
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liHzHsqBCjNELzUc
            client-secret: 36c3797a8b3d56f626bff826df32ebb06005a945

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 86400000 # 1 day

github:
  client-id: ${GITHUB_CLIENT_ID:test}
  client-secret: ${GITHUB_CLIENT_SECRET:test}
